---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - stable
    - tip
  env:
    global:
      - GO15VENDOREXPERIMENT=1
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - staticcheck $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - go test $(go list ./... | grep -v vendor)
    - make release
  deploy:
    provider: releases
    api_key:
      secure: "Q0VgFI6+j8u+WNiWMincZzSHDASUBVice8x2lUgJ9UEX29NbCsYKHhJMK90UbcoqCRojNzZ4D0JRdLuBUndxLPV3Y7Lj/QDzn3mb3QBVMr5913mqklqxx/IxvAlIYJqcJNiwJwix1QPAtsdC7kYlB1AxkI0iZVSh8o5xlXzaSVsaFxxfyYldUSstwKyo2xKqvQkJHxT0jMpRTyDzocsKqsmB6EUWEf9G0cS6B0AXU+2YihaMLO47j84nML0pD0iPvI7pB76juaiwYYR75wm88bQ+x/HvzzTTBQ2pT32D9crpCv0etnOt4wVsdglmqvAzXplpm3SgeEjNytfwXdTvcTN6ykcUuPpQl12FSOKHS2KaSj6Q/S00i6S8WcxR0WGCSaGCjozPNJH2r8CKQtcy03dmajrGpnFeAxxyPOaP3AsmLGDX93R5ZjKU5wLWTdey34E2xLdaAMg8CGl8z0WGf3siSl/ttK0+R4OS7sph/BeVQpkmX5yKDpcHWtwk1qEVs8cSoMFX+Jo6U4Y4OOEQg8M+U63idi2VEk9foVVFBjK/tGRSRV05HLR4c1B1juxvnqrU8axa6Cg3rukU9WIR8zIyLUhRrsF0ZLf113A5keLFElL60Lmfrh0P0O9W8A1UsbaIbpCqBN0m8a2m8sdzx/DIUTFbrwGfV4TYrjoo/kw="
    file:
      - cross/pastebinit-linux-amd64.md5
      - cross/pastebinit-windows-386.sha256
      - cross/pastebinit-linux-arm
      - cross/pastebinit-darwin-amd64.md5
      - cross/pastebinit-darwin-amd64
      - cross/pastebinit-solaris-amd64.md5
      - cross/pastebinit-linux-arm64.sha256
      - cross/pastebinit-linux-arm.sha256
      - cross/pastebinit-linux-386.sha256
      - cross/pastebinit-darwin-386.md5
      - cross/pastebinit-windows-386.md5
      - cross/pastebinit-freebsd-amd64.md5
      - cross/pastebinit-linux-arm64.md5
      - cross/pastebinit-linux-arm64
      - cross/pastebinit-freebsd-amd64.sha256
      - cross/pastebinit-freebsd-386.md5
      - cross/pastebinit-linux-amd64.sha256
      - cross/pastebinit-linux-386.md5
      - cross/pastebinit-freebsd-386
      - cross/pastebinit-solaris-amd64.sha256
      - cross/pastebinit-windows-amd64
      - cross/pastebinit-windows-amd64.md5
      - cross/pastebinit-windows-amd64.sha256
      - cross/pastebinit-linux-arm.md5
      - cross/pastebinit-darwin-386.sha256
      - cross/pastebinit-darwin-amd64.sha256
      - cross/pastebinit-windows-386
      - cross/pastebinit-solaris-amd64
      - cross/pastebinit-darwin-386
      - cross/pastebinit-linux-386
      - cross/pastebinit-freebsd-amd64
      - cross/pastebinit-freebsd-386.sha256
      - cross/pastebinit-linux-amd64
    skip_cleanup: true
    on:
      go: stable
      tags: true
